apiVersion: v1
kind: Service
metadata:
  name: nginx-init-service
spec:
  selector:
    app: nginx-init   # можно оставить любой, главное — создать объект с этим именем
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
